use std::convert::Infallible;
use std::sync::Arc;

use super::handlers;
use super::utils as webutils;
use crate::runtime::Runtime;
use dandelion_server::DandelionBody;
use hyper::body::Incoming;
use hyper::{Request, Response};
use log::{error, info};
use machine_interface::function_driver::thread_utils::Engine;

// Router
// ---------------------------------------------------------------------------

pub async fn route<E: Engine>(
    req: Request<Incoming>,
    runtime: Arc<Runtime<E>>,
) -> Result<Response<DandelionBody>, Infallible> {
    info!("Incoming HTTP request: {} {}", req.method(), req.uri().path());

    let result = match req.uri().path() {
        "/register/function" => handlers::register_function(req, &runtime).await,
        "/register/composition" => handlers::register_composition(req, &runtime).await,
        "/register/service" => handlers::register_service(req, &runtime).await,
        "/stats" => handlers::serve_stats(req).await,
        _ => Ok(webutils::make_bad_request("Unknown endpoint")),
    };

    match result {
        // on success, return repsonse generated by handler
        Ok(resp) => Ok(resp),
        // on error, convert error to response and return it
        Err(e) => {
            error!("Request handling failed with error: {:?}", e);
            Ok(e.to_response())
        }
    }
}
