use dandelion_commons::{
    err_dandelion, records::Recorder, DandelionError, DandelionResult, MultinodeError,
};
use dispatcher::dispatcher::DispatcherInput;
use machine_interface::composition::CompositionSet;
use prost::{
    bytes::{Buf, Bytes},
    Message,
};
use tokio::sync::oneshot;

pub mod client;
mod util;

// Todo remove when runtime is unified, and await dispatcher directly
pub enum DispatcherCommand {
    FunctionRequest {
        function_id: std::sync::Arc<String>,
        // Todo: check if we still need this for caching, otherwise, remiove and unify with temote request
        inputs: Vec<DispatcherInput>,
        is_cold: bool,
        recorder: Recorder,
        callback: oneshot::Sender<DandelionResult<(Vec<Option<CompositionSet>>, Recorder)>>,
    },
    FunctionRegistration {
        name: String,
        engine_type: machine_interface::machine_config::EngineType,
        context_size: usize,
        path: String,
        metadata: machine_interface::function_driver::Metadata,
        callback: oneshot::Sender<DandelionResult<()>>,
    },
    CompositionRegistration {
        composition: String,
        callback: oneshot::Sender<DandelionResult<()>>,
    },
    RemoteFunctionRequest {
        function_id: std::sync::Arc<String>,
        inputs: Vec<Option<CompositionSet>>,
        is_cold: bool,
        recorder: Recorder,
        callback: oneshot::Sender<DandelionResult<(Vec<Option<CompositionSet>>, Recorder)>>,
    },
    CompositionRequest {
        composition: String,
        inputs: Vec<DispatcherInput>,
        is_cold: bool,
        recorder: Recorder,
        callback: oneshot::Sender<DandelionResult<(Vec<Option<CompositionSet>>, Recorder)>>,
    },
}

// include autogenerated protobufs
mod proto {
    include!(concat!(env!("OUT_DIR"), "/multinode_proto.rs"));
}

// serialization

macro_rules! serialize {
    ($proto_msg:ident) => {{
        let mut buf = Vec::with_capacity($proto_msg.encoded_len());
        $proto_msg.encode(&mut buf).unwrap();
        prost::bytes::Bytes::from(buf)
    }};
}

fn serialize_node_info(node_info: proto::NodeInfo) -> Bytes {
    serialize!(node_info)
}

fn serialize_remote_message(worker_message: proto::RemoteMessage) -> Bytes {
    serialize!(worker_message)
}

fn serialize_queue_message(queue_message: proto::QueueMessage) -> Bytes {
    serialize!(queue_message)
}

fn deserialize_node_info(buf: impl Buf) -> DandelionResult<proto::NodeInfo> {
    match proto::NodeInfo::decode(buf) {
        Ok(node_info) => Ok(node_info),
        Err(err) => err_dandelion!(DandelionError::Multinode(
            MultinodeError::DeserializationError(format!("{:?}", err)),
        )),
    }
}

fn deserialize_remote_message(buf: Bytes) -> DandelionResult<proto::RemoteMessage> {
    match proto::RemoteMessage::decode(buf) {
        Ok(resp) => Ok(resp),
        Err(err) => err_dandelion!(DandelionError::Multinode(
            MultinodeError::DeserializationError(format!("{:?}", err)),
        )),
    }
}

fn deserialize_queue_message(buf: Bytes) -> DandelionResult<proto::QueueMessage> {
    match proto::QueueMessage::decode(buf) {
        Ok(message) => Ok(message),
        Err(err) => err_dandelion!(DandelionError::Multinode(
            MultinodeError::DeserializationError(format!("{:?}", err)),
        )),
    }
}

#[test]
fn test_serialize_invocation_request() {
    use crate::proto::{queue_message, Invocation, QueueMessage};
    use machine_interface::memory_domain::ContextTrait;

    // construct invocation data
    let expected_id = String::from("TestName");
    let item_0_0_name = "a";
    let item_0_0_data = 123u64;
    let item_1_0_name = "b";
    let item_1_0_data = 987u64;
    let item_1_1_name = "c";
    let item_1_1_data = 123u128 | (456u128 << 64);
    let mut data = vec![];
    data.extend_from_slice(&item_0_0_data.to_le_bytes());
    data.extend_from_slice(&item_1_0_data.to_le_bytes());
    data.extend_from_slice(&item_1_1_data.to_le_bytes());
    let mut in_context =
        machine_interface::memory_domain::read_only::ReadOnlyContext::new(data.into_boxed_slice())
            .expect("Should be able to create read only context");
    in_context.content = vec![
        Some(machine_interface::DataSet {
            ident: String::from("Set 0"),
            buffers: vec![machine_interface::DataItem {
                ident: String::from(item_0_0_name),
                data: machine_interface::Position {
                    offset: 0,
                    size: size_of::<u64>(),
                },
                key: 0,
            }],
        }),
        Some(machine_interface::DataSet {
            ident: String::from("Set 1"),
            buffers: vec![
                machine_interface::DataItem {
                    ident: String::from(item_1_0_name),
                    data: machine_interface::Position {
                        offset: size_of::<u64>(),
                        size: size_of::<u64>(),
                    },
                    key: 7,
                },
                machine_interface::DataItem {
                    ident: String::from(item_1_1_name),
                    data: machine_interface::Position {
                        offset: 2 * size_of::<u64>(),
                        size: size_of::<u128>(),
                    },
                    key: 14,
                },
            ],
        }),
    ];
    let inputs = machine_interface::composition::CompositionSet::from_context(in_context);

    // serialize
    let (serialized_metadata_sets, set_option) = util::composition_sets_to_proto(inputs);
    let (inputs, total_data_size) = set_option.unwrap();
    println!("serialized set: {:?}", serialized_metadata_sets);
    // not checking set names, as they are set arbitrarily, since they are ignored anyway
    // check the items
    assert_eq!(2, serialized_metadata_sets.len());
    assert_eq!(
        size_of::<u64>() as u64 + size_of::<u64>() as u64 + size_of::<u128>() as u64,
        total_data_size
    );

    let mut data_buf = prost::bytes::BytesMut::with_capacity(total_data_size as usize);
    for data_set in inputs.iter().filter_map(|item| item.as_ref()) {
        for (item, context) in data_set {
            let data_position = item.data;
            let data_slice = context
                .get_chunk_ref(data_position.offset, data_position.size)
                .unwrap();
            assert_eq!(data_position.size, data_slice.len());
            data_buf.extend_from_slice(data_slice);
        }
    }

    assert_eq!(1, serialized_metadata_sets[0].items.len());
    assert_eq!(item_0_0_name, serialized_metadata_sets[0].items[0].ident);
    assert_eq!(0, serialized_metadata_sets[0].items[0].key);
    assert_eq!(
        size_of::<u64>() as u64,
        serialized_metadata_sets[0].items[0].end_offset
    );
    assert_eq!(
        item_0_0_data,
        u64::from_le_bytes(data_buf[0..size_of::<u64>()].try_into().unwrap())
    );

    assert_eq!(2, serialized_metadata_sets[1].items.len());
    assert_eq!(item_1_0_name, serialized_metadata_sets[1].items[0].ident);
    assert_eq!(7, serialized_metadata_sets[1].items[0].key);
    assert_eq!(
        2 * size_of::<u64>() as u64,
        serialized_metadata_sets[1].items[0].end_offset
    );
    assert_eq!(
        item_1_0_data,
        u64::from_le_bytes(
            data_buf[size_of::<u64>()..2 * size_of::<u64>()]
                .try_into()
                .unwrap()
        )
    );
    assert_eq!(item_1_1_name, serialized_metadata_sets[1].items[1].ident);
    assert_eq!(14, serialized_metadata_sets[1].items[1].key);
    assert_eq!(
        2 * size_of::<u64>() as u64 + size_of::<u128>() as u64,
        serialized_metadata_sets[1].items[1].end_offset
    );
    assert_eq!(
        item_1_1_data,
        u128::from_le_bytes(
            data_buf[2 * size_of::<u64>()..(2 * size_of::<u64>() + size_of::<u128>())]
                .try_into()
                .unwrap()
        )
    );

    let request = QueueMessage {
        queue_message: Some(proto::queue_message::QueueMessage::Invocation(
            crate::proto::Invocation {
                function_id: expected_id.clone(),
                metadata_sets: serialized_metadata_sets.clone(),
                invocation_id: 7,
                caching: true,
            },
        )),
    };
    let bytes = serialize_queue_message(request);
    let invocation = bytes.clone();

    // deserialize
    let message = deserialize_queue_message(invocation)
        .unwrap()
        .queue_message
        .unwrap();
    let Invocation {
        invocation_id,
        function_id: deserialized_id,
        metadata_sets: deserialized_metadata_sets,
        caching,
    } = if let queue_message::QueueMessage::Invocation(invocation) = message {
        invocation
    } else {
        panic!("Should have deserialized an invocation");
    };
    assert_eq!(expected_id, deserialized_id);
    assert_eq!(serialized_metadata_sets, deserialized_metadata_sets);
    assert_eq!(invocation_id, 7);
    assert!(caching);

    // check the composition sets are as expected
    let mut sets = util::proto_data_sets_to_composition_sets(
        deserialized_metadata_sets,
        Some(data_buf.freeze()),
    );
    assert_eq!(2, sets.len());

    let set_0 = sets[0].take().expect("Should have Some(_) for set 0");
    assert_eq!(1, set_0.len());
    let (item_0_0, item_0_0_context) = set_0.into_iter().next().unwrap();
    assert_eq!(item_0_0_name, item_0_0.ident);
    assert_eq!(0, item_0_0.key);
    assert_eq!(size_of::<u64>(), item_0_0.data.size);
    assert_eq!(
        &item_0_0_data.to_le_bytes(),
        item_0_0_context
            .get_chunk_ref(item_0_0.data.offset, size_of::<u64>())
            .unwrap()
    );

    let set_1 = sets[1].take().expect("Should have Some(_) for set 1");
    assert_eq!(2, set_1.len());
    let mut set_1_iterator = set_1.into_iter();
    let (item_1_0, item_1_0_context) = set_1_iterator.next().unwrap();
    assert_eq!(item_1_0_name, item_1_0.ident);
    assert_eq!(7, item_1_0.key);
    assert_eq!(size_of::<u64>(), item_1_0.data.size);
    assert_eq!(
        &item_1_0_data.to_le_bytes(),
        item_1_0_context
            .get_chunk_ref(item_1_0.data.offset, size_of::<u64>())
            .unwrap()
    );
    let (item_1_1, item_1_1_context) = set_1_iterator.next().unwrap();
    assert_eq!(item_1_1_name, item_1_1.ident);
    assert_eq!(14, item_1_1.key);
    assert_eq!(size_of::<u128>(), item_1_1.data.size);
    assert_eq!(
        &item_1_1_data.to_le_bytes(),
        item_1_1_context
            .get_chunk_ref(item_1_1.data.offset, size_of::<u128>())
            .unwrap()
    );
}
