[package]
name = "machine_interface"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-machete]
ignored = ["openssl"]

[features]
# TODO remove as default feature and check everyting also works with no default feature
default = ["bytes_context"]
std = []
cheri = ["std"]
mmu = ["std"]
kvm = ["std", "dep:kvm-bindings", "dep:kvm-ioctls"]
backend_debug = []
blocking_queue = []
reqwest_io = ["std", "dep:reqwest", "dep:http", "dep:bytes", "dep:memcache"]
bytes_context = ["std", "dep:bytes"]
timestamp = ["dandelion_commons/timestamp"]
vendored-ssl = ["dep:openssl"]
test_export = []

[build-dependencies]
cmake = "0.1"

[dev-dependencies]
criterion = "0.4"
# need to lock this to older version, because morello does not yet have rustc 1.6
regex = "1.7.1"
test-log = "0.2.16"

[dependencies]
# project internal dependencies
dandelion_commons = { path = "../dandelion_commons" }
dparser = {path = "../dparser"}

# FFI dependencies
libc = "0.2"
nix = { version = "0.31", features = ["mman", "fs", "ptrace"] }

# general dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
core_affinity = { version = "0.8"}
futures = { version = "0.3.28" }
tokio = { version = "1.38.2", features = ["full"] }
log = "0.4.20"
itertools = {version = "0.11", default-features = false, features = ["use_alloc"]}
strum = { version = "0.27", features = ["derive"] }

# KVM specific dependencies
kvm-bindings = { version = "0.14", optional = true }
kvm-ioctls = { version = "0.24", optional = true }

# networking dependencies
http = { version = "1.1", optional = true }
reqwest = { version = "0.12", optional = true }
memcache = { version = "0.18.0", optional = true }
bytes = { version = "1.6", optional = true}
# To make sure we can compile everywhere. 
# This sets it for the other dependencies we have that use it.
openssl = { version = "0.10", features = ["vendored"], optional = true }

# disable benchmarks in library, to not run all unit tests on every benchmark
# also needs to be disabled for criterion flags to work that are not available for tests
[lib]
bench = false

[[bin]]
name = "mmu_worker"
required-features = ["mmu"]

[[bench]]
name = "cheri_benchmark"
harness = false

[[bench]]
name = "mmu_benchmark"
harness = false
