name: Dandelion Cargo Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev/**" ]
  #allow for manual triggering
  workflow_dispatch:

jobs:
  test:
    # set to fail fast to false so all combinations are tested
    strategy:
      fail-fast: false
      # test different available compute engines with different system engines
      matrix:
        compute_driver: [ mmu ]
        system_driver: [ reqwest_io ]
        platform: [ubuntu-24.04, ubuntu-24.04-arm]
        additional_features: [""]

        # the following additional features should be platform agnostic, thus we only test them on one specification
        include:
        - platform: ubuntu-24.04
          compute_driver: mmu
          system_driver: reqwest_io
          additional_features: "timestamp"
        
        - platform: ubuntu-24.04
          compute_driver: mmu
          system_driver: reqwest_io
          additional_features: "log_function_stdio"

    name: ${{matrix.platform}} - ${{matrix.compute_driver}}|${{matrix.system_driver}} - ${{ matrix.additional_features || 'core' }}
    runs-on: ${{matrix.platform}}

    steps:
    # check out the code
    - uses: actions/checkout@v3
    - name: setup protobuf
      run: |
        sudo apt-get update
        sudo apt-get install protobuf-compiler
    # set up feature specific prerequisits
    - name: mmu worker build
      if: ${{ matrix.compute_driver == 'mmu' }}
      run: cargo build -F ${{matrix.compute_driver}},${{matrix.additional_features}} --bin mmu_worker --target $(arch)-unknown-linux-gnu
    # run the actual tests
    - name: run tests
      run: SINGLE_CORE_MODE=true cargo test -F ${{matrix.compute_driver}},${{matrix.system_driver}},${{matrix.additional_features}}
